/**
 * Created by N1 on 9/21/2014.
 */

Language = {
    es: {
        Button: {
            Profile: "Perfil",
            Inventary: "Inventario",
            Store: "Tienda",
            World: "Mundo",
            Instructions: "Como jugar",
            InviteFriend: "Invitar un amigo",
            Resources: "Materiales",
            Selling: "Venta",
            Purchase: "Comprar",
            Sell: "Vender",
            Unlist: "Quitar",
            Attack: "Atacar",
            Select: "Seleccionar",
            Leave: "Salir",
            Trade: "Enviar",
            Send: "Enviar",
            SendTo: "Enviar a",
            Uploading: "Infectando",
            Fit: "Equipar",
            Unfit: "Quitar",
            Remove: "Eliminar",
            Guide: "Guia"


        },
        Title: {
            Materials: "Materiales",
            Stats: "Estadisticas",
            Menu: "Menu",
            Counter: "Contador"
        },
        Label: {
            Programming: "Programacion",
            Engineering: "Ingenieria",
            Storage: "Almacenamiento",
            Trade: "Comercio",
            Architecture: "Arquitectura",
            Points: "Puntos",
            ChoosePlace: "Elige tu lugar",
            Warning: "Para continuar selecciona una un lugar en el mapa.",
            Component: "Componente",
            Power: "Energia: ",
            Health: "Escudo: ",
            Price: "Precios",
            Value: "Valores"

        },
        Console: {
            VirusHigher: "El virus tiene que ser de nivel 1 o superior.",
            LackConnection: "La subida del virus fue interrumpida por falta de Conexion.",
            VirusSentTo: "El virus fue subido a ",
            Report1: "** Reporte de infeccion del virus **",
            Report2: "* Fuiste detectado y contraatacado por un usuario.",
            Report3: "* El virus fue detectado por un antivirus. Nivel del virus disminuido a ",
            Report4: "* El virus fue detectado y el proceso interrumpido.",
            Report5: "* Puntos obtenidos: ",
            Report6: "** FIN DE REPORTE **",
            MaxItems: "El otro jugador no tiene capacidad para tener mas items.",
            NotEnoughForMat1: "Faltan ",
            NotEnoughForMat2: " puntos para adquirir ",
            OneOrMore: "Tiene que ser una o mas unidades.",
            PurchaseFrom1: "El item [",
            PurchaseFrom2: " fue comprado a ",
            PurchaseFrom3: " por ",
            SellTo1: "Los [",
            SellTo2: " fueron vendidos a ",
            MaximumPoints: "No puedes recibir mas puntos. Sube de nivel el modulo de Memoria.",
            AttackFrom1: "Fuiste atacado por ",
            AttackFrom2: ". Perdiste ",
            AttackFrom3: " puntos.",
            NotEnoughForAbil1: "No tienes suficientes puntos de habilidad para subir ",
            NotEnoughForAbil2: ". Espera a subir de nivel.",
            CPUToLevel: "Tu CPU actualizado a nivel ",
            CPUPrice1: "El precio del CPU de nivel ",
            CPUPrice2: " es de ",
            CPUPrice3: " puntos.",
            ShieldToLevel: "Tu Escudo actualizado a nivel ",
            ShieldPrice1: "El precio del Escudo de nivel ",
            ShieldPrice2: " es de ",
            ShieldPrice3: " puntos. ",
            PowerToLevel: "Fuente de Energia actualizada a nivel ",
            PowerPrice1: "La Fuente de Energia de nivel ",
            PowerPrice2: " requiere ",
            PowerPrice3: " puntos.",
            VirusToLevel: "Tu Virus ahora es de nivel ",
            VirusInUse: "No puedes actualizar un virus que esta en uso.",
            VirusPrice1: "El precio de un Virus de nivel ",
            VirusPrice2: " es de ",
            VirusPrice3: " puntos.",
            MemoryToLevel: "Tu Memoria ahora es de nivel ",
            MemoryPrice1: "El precio de la Memoria de nivel ",
            MemoryPrice2: " es de ",
            MemoryPrice3: " puntos.",
            HDDToLevel: "Tu Almacenamiento ahora es de nivel ",
            HDDPrice1: "El precio del Almacenamiento de nivel ",
            HDDPrice2: " es de ",
            HDDPrice3: " puntos.",
            NetworkToLevel: "Tu Conexion ahora es de nivel ",
            NetworkPrice1: "El precio de la Conexion de nivel ",
            NetworkPrice2: " es de ",
            NetworkPrice3: " puntos.",
            CPULower: "El nivel del CPU fue disminuido por un ataque.",
            VirusLower: "El nivel del Virus fue disminuido por un ataque.",
            PowerLower: "El nivel del modulo de Energia fue disminuido por un ataque.",
            ShieldLower: "El nivel del Escudo fue dismiuido por un ataque.",
            From: " de los ",
            Have: "Tienes "
        },
        Loading: {
            Step1: "Esperando sesion...",
            Step2: "Iniciando sesion.",
            Step3: "Bienvenido, ",
            Step4: "Descargando datos de usuario....",
            Step5: "Cargando niveles...",
            Step6: "Inicializado modulos..",
            Step7: "Llenando inventario.",
            Step8: "Iniciando el sistema",
            Login: "Para iniciar el juego presiona el boton de login.",
            Title: "Bienvenido a Bitquest",
            Warning: "Si el juego no inicia presiona F5 para actualizar."
        },
        Description: {
            infoText1: "Bienvenido a Bitquest. Para continuar presiona el boton de Ok.",
            infoText2: "El componente CPU sirve para obtener puntos. Se puede subir de nivel dandole click.",
            infoText3: "El escudo Antivirus te defiende de los ataques de Virus. Cuanto mayor nivel mas vida y mas defensa.",
            infoText4: "El Virus sirve para infectar otros sistemas en la red, o seleccionar un sistema en el mapa e infectarlo manualmente. Se puede obtener puntos de esta manera. <br><br>El nivel de Conexion mejora la velocidad de infeccion.",
            infoText5: "La Fuente de Energia mantiene el sistema con puntos de energia. Cuanto mayor el nivel mejor el rendimiento (se puede mejorar con modulos del inventario).",
            infoText6: "Los materiales sirven para la subida de nivel de los componentes del computador. Se puede acelerar el proceso con Programacion o Ingenieria.",
            infoText7: "El inventario mantiene los modulos almacenados en el Disco Duro. Se puede subir el componente Disco Duro para obtener mas lugar de almacenamiento.",
            infoText8: "Las barras de Energia y Escudo indican el estado actual del sistema. Es preferible tener siempre los stats altos para que el computador funcione bien.",
            infoText9: "Aca se indica la cantidad de puntos que se tiene, y cuantos puntos puede almacenar el componente de memoria RAM. Abajo aparece en verde la cantidad de puntos que faltan para subir de nivel.<br><br>La capacidad de almacenamiento se puede mejorar subiendo el modulo de RAM."
        }
    },

    en: {
        Button: {
            Profile: "Profile",
            Inventary: "Inventory",
            Store: "Store",
            World: "World",
            Instructions: "Details",
            InviteFriend: "Invite a friend",
            Resources: "Resources",
            Selling: "Sell",
            Purchase: "Purchase",
            Sell: "Sell",
            Unlist: "Unlist",
            Attack: "Attack",
            Select: "Select",
            Leave: "Leave",
            Trade: "Send",
            Send: "Attack",
            SendTo: "Send to",
            Uploading: "Uploading",
            Fit: "Fit",
            Unfit: "Unfit",
            Remove: "Remove",
            Guide: "Guide"


        },
        Title: {
            Materials: "Resources",
            Stats: "Statistics",
            Menu: "Menu",
            Counter: "Counter"
        },
        Label: {
            Programming: "Programming",
            Engineering: "Engineering",
            Storage: "Storage",
            Trade: "Trade",
            Architecture: "Architecture",
            Points: "Points",
            ChoosePlace: "Choose a place to install your system",
            Warning: "To start playing choose a place in the map.",
            Component: "Component",
            Power: "Power: ",
            Health: "Health: ",
            Price: "Prices",
            Value: "Values"
        },
        Console: {
            VirusHigher: "The virus has to be at least level 1 or higher.",
            LackConnection: "The uploading has been interrupted by the level of Network.",
            VirusSentTo: "The virus was uploaded to ",
            Report1: "** Virus infection report **",
            Report2: "* The virus was detected and your system received damage.",
            Report3: "* The virus was detected by an antivirus and the level lowered to ",
            Report4: "* The virus was detected and the process interrupted.",
            Report5: "* Points obtained: ",
            Report6: "** EOR **",
            MaxItems: "The other user lacks in capacity to have more items..",
            NotEnoughForMat1: "You lack ",
            NotEnoughForMat2: " Points to obtain ",
            OneOrMore: "The quantity must be 1 or more.",
            PurchaseFrom1: "The item [",
            PurchaseFrom2: " was purchased at a price of ",
            PurchaseFrom3: " Points by ",
            SellTo1: "The items [",
            SellTo2: " were sold at ",
            MaximumPoints: "You can't have more points. Level up your Memory.",
            AttackFrom1: "You received an attack from ",
            AttackFrom2: ". The loss was of ",
            AttackFrom3: " Points.",
            NotEnoughForAbil1: "You lack Ability points to upgrade ",
            NotEnoughForAbil2: ". Wait for a system upgrade to obtain more.",
            CPUToLevel: "Your CPU was upgraded to level ",
            CPUPrice1: "The price of a CPU ",
            CPUPrice2: " is of ",
            CPUPrice3: " Points.",
            ShieldToLevel: "Your Shield was upgraded to level ",
            ShieldPrice1: "The price of a Shield ",
            ShieldPrice2: " is of ",
            ShieldPrice3: " Points. ",
            PowerToLevel: "The module of Power was upgraded to level ",
            PowerPrice1: "The price of the module of Power ",
            PowerPrice2: " requires ",
            PowerPrice3: " Points.",
            VirusToLevel: "Your Virus was updated to level ",
            VirusInUse: "You can't update a virus while in use.",
            VirusPrice1: "The price of a Virus ",
            VirusPrice2: " is of ",
            VirusPrice3: " Points.",
            MemoryToLevel: "Your Memory was upgraded to level ",
            MemoryPrice1: "The price of Memory ",
            MemoryPrice2: " is of ",
            MemoryPrice3: " Points.",
            HDDToLevel: "The Storage was upgraded to level ",
            HDDPrice1: "The price of Storage ",
            HDDPrice2: " is of ",
            HDDPrice3: " Points.",
            NetworkToLevel: "Your Network was upgraded to level ",
            NetworkPrice1: "The price of Network ",
            NetworkPrice2: " is of ",
            NetworkPrice3: " Points.",
            CPULower: "The level of CPU has been lowered by an attack.",
            VirusLower: "The level of Virus has been lowered by an attack.",
            PowerLower: "The level of Power module has been lowered by an attack.",
            ShieldLower: "The level of Shield has been lowered by an attack.",
            From: " from ",
            Have: " You have "
        },
        Loading: {
            Step1: "Awaiting session...",
            Step2: "Loggin in.",
            Step3: "Good to see you, ",
            Step4: "User data loaded....",
            Step5: "Levels loaded...",
            Step6: "Modules initialized..",
            Step7: "Inventory filled.",
            Step8: "Initializing system",
            Login: "Press the login button to enter the game.",
            Title: "Welcome to Bitquest",
            Warning: "If the game won't start hit F5 to refresh."
        },
        Description: {
            infoText1: "Welcome to Bitquest. To continue press Ok.",
            infoText2: "The CPU makes points. You can increase the level of the component by clicking it.",
            infoText3: "The Antivirus defends you from incoming attacks. A higher level of the Antivirus increases your system performance and shield.",
            infoText4: "The Virus can infect other system on the grid, or infect a specific system on the map manually. You can obtain points this way.<br><br>The level of Conection increases the speed of infection.",
            infoText5: "The Power Grid increases the points of Energy. The higher the level of it the better is the performance of the system (you can make it better with modules from the inventory).",
            infoText6: "The materials are used in upgrades of your system components. You can increase the speed of material gain by upgrading Programming or Engineering stats.",
            infoText7: "The inventory contains modules stored on the Hard Drive. You can upgrade your Hard Drive to increase the slot capacity.",
            infoText8: "The Enery and Shield bars show your computer stats. It's adviced to maintain the bars full to keep the system in a good state.",
            infoText9: "Here you can see the quantity of points you have, and how many points can store your component of RAM. Below in green shows the lacking points to level up.<br><br>The capacity of storage of RAM can be increased by upgrading your RAM."
        }

    }
};